### PR TITLE
add pod spec

### PR DESCRIPTION
**Pull request by solos**
add pod spec
split croaring and SwiftRoaring pod spec

### CODE REVIEW

**Comment by lemire** [comment]
@piotte13 Can you check your  deploy-to-gh-pages.sh script? It seems to be failing on travis. I am not sure why they are needed as part of the unit tests.

@solos It would be useful to add tests. Or, at least, I'd like to manually verify that it works. Can you provide instructions on how to build with cocoapods?

**Comment by solos** [comment]
I test it by cd the repo dir and run pod spec lint SwiftRoaring.podspec  --allow-warnings  and pod lib lint croaring.podspec  --verbose --allow-warnings

**Comment by solos** [comment]
I found my app crash,  because of bad address exception.So i use raw bitset instead.  Maybe  the way i used has some problems.

**Comment by lemire** [comment]
> I found my app crash, because of bad address exception.So i use raw bitset instead. Maybe the way i used has some problems.

Can you share the code?

**Comment by lemire** [comment]
I confirm that it looks like it is working:

```
$ pod spec lint SwiftRoaring.podspec --allow-warnings
(...)
SwiftRoaring.podspec passed validation.
```

```
$ pod lib lint croaring.podspec --verbose --allow-warnings
(...)
croaring passed validation.
```

Good work.

I recommend mergin.

**Comment by lemire** [comment]
I have merged your PR at
https://github.com/RoaringBitmap/SwiftRoaring

If you have a programming issue, please take it there.

**Comment by solos** [comment]
thanks.

**Pull request closed without merging**
